export const GET_SHOW_IMAGE_BEGIN = 'GET_SHOW_IMAGE_BEGIN';
export const GET_SHOW_IMAGE_SUCCESS = 'GET_SHOW_IMAGE_SUCCESS';
export const GET_SHOW_IMAGE_FAILURE = 'GET_SHOW_IMAGE_FAILURE';

export const GET_SHOW_INFO_BEGIN = 'GET_SHOW_INFO_BEGIN';
export const GET_SHOW_INFO_SUCCESS = 'GET_SHOW_INFO_SUCCESS';
export const GET_SHOW_INFO_FAILURE = 'GET_SHOW_INFO_FAILURE';

export const GET_SHOW_SEASONS_BEGIN = 'GET_SHOW_SEASONS_BEGIN';
export const GET_SHOW_SEASONS_SUCCESS = 'GET_SHOW_SEASONS_SUCCESS';
export const GET_SHOW_SEASONS_FAILURE = 'GET_SHOW_SEASONS_FAILURE';

export const GET_SHOW_SEASON_EPS_BEGIN = 'GET_SHOW_SEASON_EPS_BEGIN';
export const GET_SHOW_SEASONS_EPS_SUCCESS = 'GET_SHOW_SEASONS_EPS_SUCCESS';
export const GET_SHOW_SEASONS_EPS_FAILURE = 'GET_SHOW_SEASONS_EPS_FAILURE';

export const GET_EP_INFO_BEGIN = 'GET_EP_INFO_BEGIN';
export const GET_EP_INFO_SUCCESS = 'GET_EP_INFO_SUCCESS';
export const GET_EP_INFO_FAILURE = 'GET_EP_INFO_FAILURE';

export const SET_CURRENT_SEASON = 'SET_CURRENT_SEASON';